"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Sparkles } from "lucide-react"
import { useState, useTransition } from "react"
import { generateQuestionAnswer } from "@/app/actions/ai-actions"
import { useRouter } from "next/navigation"

type Question = {
  id: string
  ai_answer: string | null
}

export function AIAnswerSection({ question }: { question: Question }) {
  const [isPending, startTransition] = useTransition()
  const [error, setError] = useState<string | null>(null)
  const router = useRouter()

  const handleGenerate = () => {
    setError(null)
    startTransition(async () => {
      try {
        await generateQuestionAnswer(question.id)
        router.refresh()
      } catch (err) {
        console.error("Error generating answer:", err)
        setError("Failed to generate answer. Please try again.")
      }
    })
  }

  if (!question.ai_answer) {
    return (
      <Card className="border-accent/20 bg-accent/5">
        <CardContent className="flex flex-col items-center justify-center py-12 text-center">
          <div className="mb-4 rounded-full bg-accent/10 p-4">
            <Sparkles className="h-8 w-8 text-accent" />
          </div>
          <h3 className="mb-2 text-lg font-semibold">Get an AI-Powered Answer</h3>
          <p className="mb-4 text-sm text-muted-foreground">
            Generate an instant answer using AI based on university information and context.
          </p>
          {error && <p className="mb-4 text-sm text-destructive">{error}</p>}
          <Button onClick={handleGenerate} disabled={isPending} className="gap-2">
            <Sparkles className="h-4 w-4" />
            {isPending ? "Generating..." : "Generate AI Answer"}
          </Button>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="border-accent/20 bg-accent/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-accent">
          <Sparkles className="h-5 w-5" />
          AI-Generated Answer
        </CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-pretty leading-relaxed whitespace-pre-wrap">{question.ai_answer}</p>
        <div className="mt-4 rounded-lg bg-muted/50 p-3 text-xs text-muted-foreground">
          This answer was generated by AI and may not be completely accurate. Please verify important information with
          official university sources.
        </div>
      </CardContent>
    </Card>
  )
}
